sudo: required 
services: 
  - docker

before_install: 
  - docker build -t dennisvankekem/docker-react -f Dockerfile.dev .

script:
  - docker run dennisvankekem/docker-react npm run test -- --coverage